version: "3.5"

services:
  auth:
    build: docker/roadrunner
    tty: true
    stdin_open: true
    volumes:
      - ./services/auth:/var/www/app
    expose:
      - "80"
    ports:
      - "${LOCAL_AUTH_PORT}:80"
    environment:
      - "DEBUG=${DEBUG}"
      - "ADMINS=${ADMINS}"
      - "MANAGERS=${MANAGERS}"
      - "ACCOUNTANTS=${ACCOUNTANTS}"
      - "DEVELOPERS=${DEVELOPERS}"
      - "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}"
      - "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}"
      - "OAUTH_CLIENT_REDIRECT=${OAUTH_CLIENT_REDIRECT}"
    depends_on:
      - message-bus
  accounting:
    build: docker/roadrunner
    tty: true
    stdin_open: true
    volumes:
      - ./services/accounting:/var/www/app
    expose:
      - "80"
    depends_on:
      - auth
      - message-bus
  analytics:
    build: docker/roadrunner
    tty: true
    stdin_open: true
    volumes:
      - ./services/analytics:/var/www/app
    expose:
      - "80"
    environment:
      - "DEBUG=${DEBUG}"
    depends_on:
      - auth
      - message-bus
  task-tracker:
    build: docker/roadrunner
    tty: true
    stdin_open: true
    volumes:
      - ./services/task-tracker:/var/www/app
    expose:
      - "80"
    environment:
      - "DEBUG=${DEBUG}"
    depends_on:
      - auth
      - message-bus
  api:
    build: docker/roadrunner
    tty: true
    stdin_open: true
    depends_on:
      - accounting
      - analytics
      - auth
      - task-tracker
    volumes:
      - ./services/api:/var/www/app
    expose:
      - "80"
    environment:
      - "DEBUG=${DEBUG}"
    ports:
      - "${LOCAL_API_PORT}:80"
  message-bus:
    image: blacktop/kafka:3.1
    ports:
      - "${ZOOKEEPER_PORT}:2181"
      - "${KAFKA_PORT}:9092"
networks:
  default:
    name: chickinet
    driver: bridge
